#!/usr/bin/env bash

# ship-setup-isolated-env.sh — Provision or attach a repo-local isolated app env
# for /ship and persist source-able exports into the ship working directory.
#
# Creates:
#   ${CLAUDE_SHIP_DIR:-tmp/ship}/isolated-env.sh
#   ${CLAUDE_SHIP_DIR:-tmp/ship}/isolated-env.json
#
# Usage:
#   ship-setup-isolated-env.sh --feature <feature-name> [--name <env-name>]
#
# The helper prefers `pnpm setup-dev --isolated <name>` when the repo exposes
# that entrypoint, otherwise it falls back to `./scripts/isolated-env.sh setup`.
# Export capture always comes from `./scripts/isolated-env.sh env <name>`.

set -euo pipefail

SHIP_DIR="${CLAUDE_SHIP_DIR:-tmp/ship}"
FEATURE_NAME=""
ENV_NAME=""

usage() {
  cat <<'EOF'
Usage:
  ship-setup-isolated-env.sh --feature <feature-name> [--name <env-name>]

Options:
  --feature <feature-name>  Required. Source feature name or slug.
  --name <env-name>         Optional explicit isolated env name override.
EOF
}

slugify_name() {
  local raw="$1"
  printf '%s' "$raw" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g' \
    | cut -c1-63
}

validate_name() {
  local name="$1"
  if [[ ! "$name" =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]]; then
    echo "Error: isolated env name must be 1-63 chars of lowercase letters, numbers, and hyphens (got '$name')" >&2
    exit 1
  fi
}

has_isolated_env_cli() {
  [[ -f "scripts/isolated-env.sh" ]]
}

has_setup_dev_isolated() {
  command -v pnpm >/dev/null 2>&1 \
    && [[ -f package.json ]] \
    && command -v jq >/dev/null 2>&1 \
    && jq -e '.scripts["setup-dev"]? != null' package.json >/dev/null 2>&1
}

write_env_file() {
  local env_output="$1"
  local env_file="$2"
  cat > "$env_file" <<EOF
#!/usr/bin/env bash
# Generated by ship-setup-isolated-env.sh for feature '${FEATURE_NAME}'
# Source this file before running repo/app commands that need the isolated env.
${env_output}
EOF
  chmod +x "$env_file"
}

metadata_json_for_exports() {
  local export_lines="$1"
  printf '%s\n' "$export_lines" \
    | python3 -c '
import json, re, sys
exports = {}
pattern = re.compile(r"^\s*export\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$")
for line in sys.stdin.read().splitlines():
    match = pattern.match(line)
    if not match:
        continue
    key, raw = match.groups()
    value = raw
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("\"", "\x27"):
        value = value[1:-1]
    exports[key] = value
print(json.dumps(exports))
'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --feature) FEATURE_NAME="$2"; shift 2 ;;
    --name) ENV_NAME="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *)
      echo "Error: unknown option '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$FEATURE_NAME" ]]; then
  echo "Error: --feature is required" >&2
  usage >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq is required but not found" >&2
  exit 1
fi

mkdir -p "$SHIP_DIR"

if [[ -z "$ENV_NAME" ]]; then
  ENV_NAME="$(slugify_name "$FEATURE_NAME")"
fi
validate_name "$ENV_NAME"

ENV_FILE="${SHIP_DIR}/isolated-env.sh"
METADATA_FILE="${SHIP_DIR}/isolated-env.json"
NOW_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

if ! has_isolated_env_cli; then
  echo "Error: scripts/isolated-env.sh is required so /ship can capture source-able env exports." >&2
  exit 1
fi

PROVISIONER="scripts/isolated-env.sh"
SETUP_COMMAND="./scripts/isolated-env.sh setup ${ENV_NAME}"
ATTACHED_EXISTING=false

set +e
EXISTING_ENV_OUTPUT="$(./scripts/isolated-env.sh env "${ENV_NAME}" 2>/dev/null)"
EXISTING_STATUS=$?
set -e

if [[ $EXISTING_STATUS -eq 0 ]] && [[ -n "$EXISTING_ENV_OUTPUT" ]]; then
  ATTACHED_EXISTING=true
  ENV_OUTPUT="$EXISTING_ENV_OUTPUT"
else
  if has_setup_dev_isolated; then
    PROVISIONER="pnpm setup-dev --isolated"
    SETUP_COMMAND="pnpm setup-dev --isolated ${ENV_NAME}"
  fi

  bash -c "$SETUP_COMMAND"
  ENV_OUTPUT="$(./scripts/isolated-env.sh env "${ENV_NAME}")"
fi

if [[ -z "$ENV_OUTPUT" ]]; then
  echo "Error: scripts/isolated-env.sh env '${ENV_NAME}' returned no exports" >&2
  exit 1
fi

write_env_file "$ENV_OUTPUT" "$ENV_FILE"

STATE_FILE=""
if [[ -f ".isolated-envs/${ENV_NAME}.json" ]]; then
  STATE_FILE=".isolated-envs/${ENV_NAME}.json"
fi

EXPORTED_VARS_JSON="$(metadata_json_for_exports "$ENV_OUTPUT")"

jq -n \
  --arg name "$ENV_NAME" \
  --arg feature "$FEATURE_NAME" \
  --arg envFile "$ENV_FILE" \
  --arg metadataFile "$METADATA_FILE" \
  --arg stateFile "$STATE_FILE" \
  --arg provisioner "$PROVISIONER" \
  --arg setupCommand "$SETUP_COMMAND" \
  --arg envCommand "./scripts/isolated-env.sh env ${ENV_NAME}" \
  --arg teardownCommand "./scripts/isolated-env.sh down ${ENV_NAME}" \
  --arg now "$NOW_UTC" \
  --argjson active true \
  --argjson attachedExisting "$ATTACHED_EXISTING" \
  --argjson exportedVars "$EXPORTED_VARS_JSON" \
  '{
    name: $name,
    featureName: $feature,
    envFile: $envFile,
    metadataFile: $metadataFile,
    stateFile: (if $stateFile == "" then null else $stateFile end),
    active: $active,
    attachedExisting: $attachedExisting,
    provisioner: $provisioner,
    setupCommand: $setupCommand,
    envCommand: $envCommand,
    teardownCommand: $teardownCommand,
    provisionedAt: $now,
    exportedVars: $exportedVars
  }' > "$METADATA_FILE"

echo "Isolated env ready:"
echo "  Name:         $ENV_NAME"
echo "  Env file:     $ENV_FILE"
echo "  Metadata:     $METADATA_FILE"
echo "  Attached:     $ATTACHED_EXISTING"
echo "  Setup path:   $PROVISIONER"
